failure-threshold: warning
format: tty
ignored:
  - DL3000
label-schema:
  author: Rafa Adorna
  contact: thaeimos
  created: 2022-10-07
  version: 0.1.1
no-color: false
no-fail: false
trustedRegistries: 
  - docker.io
